[package]
name = "emscripten-tokio"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "macros", "sync", "time", "net", "io-util"] }
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = { version = "0.1", features = ["channel"] }
bytes = "1"

[profile.release]
opt-level = "s"

# Tokio on Emscripten patchset, pending upstream PRs.
# Pending libc@0.2.190
[patch.crates-io]
libc = { git = "https://github.com/rust-lang/libc", branch = "libc-0.2" }
# Pending https://github.com/tokio-rs/tokio/pull/8484
tokio = { git = "https://github.com/guybedford/tokio", tag = "1.53.1-cf.emscripten" }
tokio-macros = { git = "https://github.com/guybedford/tokio", tag = "1.53.1-cf.emscripten" }
# Pending https://github.com/tokio-rs/mio/pull/1969
mio = { git = "https://github.com/guybedford/mio", tag = "1.2.3-cf.emscripten" }
